### ISSUE TITLE
Not sure if it's not working or I'm doing something wrong

### ISSUE THREAD

**Issue by JohnBakery** [fjarrett/expire-passwords#13]
I installed Expire Passwords on WP 3.5 and decided to test in on a single account. I assigned a new role to an existing account and set passwords to expire after one day for that role. I waited over 24 hours, but the password never expired and under the Password Reset column in the user list section of WP it simply shows "—".
What am I doing wrong?

**Comment by frankiejarrett** [comment]
@JohnBakery This plugin requires WordPress 4.0 or higher - I suspect this could be the problem.

https://github.com/fjarrett/expire-passwords/blob/8c5d02ddae762da88bf6446c54967df069bbde7f/readme.txt#L4
